---
- name:             Prometheus node_exporter installation
  hosts:            all
  gather_facts:     false
  vars:
    pme_version:    "0.18.1"
  tasks:
    - name:         "Include prometheus_node_exporter"
      include_role:
        name:       "prometheus_node_exporter"
