---
- name:             Prometheus node_exporter installation
  hosts:            all
  become:           true
  gather_facts:     false
  vars:
    pne_version:    "1.0.X"
  tasks:
    - name:         "Include prometheus_node_exporter"
      include_role:
        name:       "prometheus_node_exporter"
