---
- name:               Prometheus configuration
  hosts:              all
  gather_facts:       false
  vars:
    awx_bearer_token: "XXXXXXXXXXXXXXXXXXX"
  tasks:
    - name:           Ensure Prometheus is configured
      template:
        src:          prometheus.yml.j2
        dest:         /home/vagrant/docker/prometheus.yml
        owner:        vagrant
        group:        vagrant
        mode:         '0644'
