---
- name:               Prometheus configuration
  hosts:              all
  gather_facts:       false
  vars:
    awx_bearer_token: "7wYT58bphu3aZ2dtuLcDyx9dzvVAXT"
  tasks:
    - name:           Ensure Prometheus is configured
      template:
        src:          prometheus.yml.j2
        dest:         /home/vagrant/docker/prometheus.yml
        owner:        vagrant
        group:        vagrant
        mode:         '0644'
      notify:        RESTART_DCO
  handlers:
    - name:           Restart docker compose stack
      command:        docker-compose restart
      args:
        chdir:        /home/vagrant/docker
        creates:      /path/to/database
      listen:       RESTART_DCO
